name: Activity Radar
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  activity-radar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ashishghadigaonkar
          template: classic
          base: ""
          
          # Focus only on the Activity Overview summary (Radar Chart)
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 14
          plugin_habits_charts_type: radar
          
          filename: activity-radar.svg
